['hzk_new', 'dycj', 'hzk', 'cjw', 'zqw_new', 'zwwcj', 'zgwcj', 'common', 'lzk_new', 'qjw', '21jjw', 'zzw', 'zqzx', 'thsjj', 'gmw_new', 'hqcj_new', 'liejin99', 'zgqyxww', 'fhwcj', 'rmwcj', 'ecncj', 'swcj', 'zgjjw', 'zgjyw', 'yswcj', 'cjsb', 'lzk', 'dywcj', 'jrj', 'zgggb_new', 'dfcj_new', 'jjgcw', 'xhcj', 'lhlc', 'mrjjxw', 'xhcj_new', 'zqrb', '163', 'zgzqw', 'txcj', 'zqsb', 'jcwjr', 'yszq']
Start crawling ... 
start pipeline for  中证网 1
start pipeline for  全景网 2
中证网 finished cost 4.811807s
全景网 finished cost 23.564506s
start pipeline for  经济观察网 3
start pipeline for  第一财经 4
第一财经 finished cost 4.508333s
经济观察网 finished cost 8.473565s
start pipeline for  腾讯财经 5
start pipeline for  21经济网 6
21经济网 finished cost 5.939358s
腾讯财经 finished cost 6.111177s
start pipeline for  财经网 7
start pipeline for  ECN财经 8
ECN财经 finished cost 1.179700s
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 176, in run
    transformer.process(news_info)
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXProcessors.py", line 107, in process
    value = MySQLdb.escape_string(value)
TypeError: must be string or read-only buffer, not None
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 176, in run
    transformer.process(news_info)
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXProcessors.py", line 107, in process
    value = MySQLdb.escape_string(value)
TypeError: must be string or read-only buffer, not None
财经网 finished cost 3.500794s
start pipeline for  中国改革报 9
start pipeline for  中国证券网 10
中国改革报 finished cost 32.473297s
中国证券网 finished cost 67.798405s
start pipeline for  人民网财经 11
start pipeline for  证券日报 12
证券日报 finished cost 40.535666s
人民网财经 finished cost 44.055143s
start pipeline for  央视证券 13
start pipeline for  证券时报 14
央视证券 finished cost 11.985542s
证券时报 finished cost 315.889734s
start pipeline for  中青网 15
start pipeline for  环球财经 16
环球财经 finished cost 23.930222s
中青网 finished cost 301.666017s
start pipeline for  东方财经 17
start pipeline for  长江商报 18
长江商报 finished cost 78.003918s
东方财经 finished cost 100.304918s
start pipeline for  大洋网财经 19
start pipeline for  凤凰网财经 20
凤凰网财经 finished cost 101.062178s
大洋网财经 finished cost 149.808859s
start pipeline for  金融界 21
start pipeline for  荆楚网金融 22
荆楚网金融 finished cost 19.090313s
金融界 finished cost 1040.951033s
start pipeline for  龙虎理财 23
start pipeline for  每日经济新闻 24
龙虎理财 finished cost 6.365805s
每日经济新闻 finished cost 98.896410s
start pipeline for  舜网财经 25
start pipeline for  同花顺经济 26
舜网财经 finished cost 23.201632s
同花顺经济 finished cost 423.195820s
start pipeline for  同花顺猎金 27
start pipeline for  证券之星 28
同花顺猎金 finished cost 36.156790s
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: </span><a href="http://news.stockstar.com/SS2017122300000295.shtml">海关总署：中国11月汽油出口同比上涨11.2%至104万吨</a></li> <li><span>2017-12-23 10:26:02
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: </span><a href="http://news.stockstar.com/SS2017122300000295.shtml">海关总署：中国11月汽油出口同比上涨11.2%至104万吨</a></li> <li><span>2017-12-23 10:26:02
证券之星 finished cost 456.355682s
start pipeline for  中国经济网 29
start pipeline for  中国经营网 30
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  07:10' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  07:10' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  09:14' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  09:14' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:58' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:58' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  15:16' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  15:16' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:58' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:58' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:53' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:53' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/07/21  07:59' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/07/21  07:59' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  14:34' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  14:34' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:28' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:28' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:30' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:30' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:36' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:36' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/14  12:05' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/14  12:05' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  07:16' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  07:16' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/07/21  07:57' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/07/21  07:57' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  09:10' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  09:10' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  07:29' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  07:29' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:22' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  07:22' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/19  06:42' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/19  06:42' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  10:34' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  10:34' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/20  07:39' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/20  07:39' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  08:10' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/22  08:10' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  07:41' does not match format '               %Y/%m/%d  %H:%M               '
Traceback (most recent call last):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXNewsETL.py", line 166, in run
    for news_info in crawler.run():
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 181, in run
    for news_info in self.generate_url_from_list(content):
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 371, in generate_url_from_list
    news_info for news_info in self.parse_list_page(content)]
  File "/home/zhangxiang/news_crawler/code/XX_Crawler/XXCrawlers.py", line 312, in parse_list_page
    value = datetime.strptime(value, self.pub_date_format)
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2017/12/23  07:41' does not match format '               %Y/%m/%d  %H:%M               '
中国经济网 finished cost 59.615256s
中国经营网 finished cost 309.929873s
start pipeline for  中国企业新闻网 31
start pipeline for  中文网财经 32
中文网财经 finished cost 15.608237s
中国企业新闻网 finished cost 21.560387s
Crawling finished ... cost 3372.132581s 
